#spring:
#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: scm-orderEvents  # topic name
##          content-type: application/json
#          consumer:
#            header-mode: raw
#            back-off-multiplier: 2
#            back-off-initial-interval: 10000
#            max-attempts: 2
        #output:
        #  destination: scm-orderEvents  # topic name
        #  content-type: application/json
 #     kafka:
 #         binder:
 #             brokers: localhost
 #             defaultBrokerPort: 9092
 #             zkNodes: localhost
 #             defaultZkPort: 2181
 #         bindings:
 #           input:
 #             consumer:
 #               configuration:
 #                 value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
 #                 key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
 #               enableDlq: true